// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwhqt1t4mDs75W-dQZq_hxK3GIfcVZmd4',
    appId: '1:719683381257:web:54f990e0cfddd1c1fdb0d8',
    messagingSenderId: '719683381257',
    projectId: 'railrelax-abaac',
    authDomain: 'railrelax-abaac.firebaseapp.com',
    storageBucket: 'railrelax-abaac.firebasestorage.app',
    measurementId: 'G-GQ9L6S0ZY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8NLCfFYj9X5Cktdk5dRjegfUHbmeGv7Q',
    appId: '1:719683381257:android:3e13922244fca81bfdb0d8',
    messagingSenderId: '719683381257',
    projectId: 'railrelax-abaac',
    storageBucket: 'railrelax-abaac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3WWWIhFFStHbk-EFQogR5xUktBp8Sywc',
    appId: '1:719683381257:ios:7da0e5092a983facfdb0d8',
    messagingSenderId: '719683381257',
    projectId: 'railrelax-abaac',
    storageBucket: 'railrelax-abaac.firebasestorage.app',
    iosBundleId: 'com.example.railrelax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3WWWIhFFStHbk-EFQogR5xUktBp8Sywc',
    appId: '1:719683381257:ios:7da0e5092a983facfdb0d8',
    messagingSenderId: '719683381257',
    projectId: 'railrelax-abaac',
    storageBucket: 'railrelax-abaac.firebasestorage.app',
    iosBundleId: 'com.example.railrelax',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwhqt1t4mDs75W-dQZq_hxK3GIfcVZmd4',
    appId: '1:719683381257:web:773fd808ce6810effdb0d8',
    messagingSenderId: '719683381257',
    projectId: 'railrelax-abaac',
    authDomain: 'railrelax-abaac.firebaseapp.com',
    storageBucket: 'railrelax-abaac.firebasestorage.app',
    measurementId: 'G-5WB52SKBQY',
  );
}
